name: Provision t3.micro EC2

env:
      HETZNER_IP: ${{ secrets.HETZNER_IP }}
on:
  workflow_dispatch:
    inputs:
      ec2-name:
        description: EC2 name
        required: true
        default: 'App Server'
        type: string
jobs:
  provision-ec2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: '${{ secrets.TF_USER_AWS_KEY }}'
          aws-secret-access-key: '${{ secrets.TF_USER_AWS_SECRET }}'
          aws-region: us-east-2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform Apply
        id:   apply
        env:
          TF_VAR_ec2_name:  "${{ github.event.inputs.ec2-name }}"
        run: |
          cd /home/runner/work/github_actionsEC2/github_actionsEC2
          terraform init
          terraform validate
          terraform plan 
          terraform apply -auto-approve -json > tf_output.json
        working-directory: ./
          
      - name: Parse Terraform output
        id: parse_output
        run: |
          IP=$(terraform output -json | jq -r '.instance_public_ip.value')
          echo "instance_public_ip: $IP"
          echo "::set-output name=HETZNER_IP::$IP"
        working-directory: ./

      - name: Add Hetzner IP to GitHub Secrets
        run: |
          echo $HETZNER_IP > /tmp/hetzner_ip.txt
        env:
          HETZNER_IP: ${{ steps.parse_output.outputs.HETZNER_IP }}

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml
          directory: ./
          key: ${{secrets.SSH_PRIVATE_KEY}}
          inventory: |
            [all]
            ${{secrets.HETZNER_IP}}
